repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
    -   id: ruff-check
        args: [ --fix ]
    -   id: ruff-format

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
    -   id: bandit
        args: ["-r", "src/", "-ll"]
        pass_filenames: false

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["src"]
        pass_filenames: false

    -   id: pytest-unit
        name: pytest-unit
        entry: pytest tests/unit
        language: system
        pass_filenames: false
        always_run: true
