repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: powershell.exe -Command "$env:PYTHONPATH += ';./src'; mypy --ignore-missing-imports --disable-error-code import-untyped src/"
        language: system
        types: [python]
        pass_filenames: false

    -   id: pytest-unit
        name: pytest-unit
        entry: pytest tests/unit
        language: system
        pass_filenames: false
        always_run: true
